server:
  port: 8080
  servlet:
    contextPath: /blog

spring:
  application:
    name: blog-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    username: postgres
    password: qwert12
    url: jdbc:postgresql://localhost:5432/blogs
    driverClassName: org.postgresql.Driver



logging:
  level:
    root: ERROR
    org.hibernate.SQL: ERROR
    org.springframework.data: ERROR
    com.example.blog_app: INFO
  file:
    name: logs/blogging-service.log


